# Generated by Django 5.1.3 on 2024-11-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
