# Generated by Django 5.1.3 on 2024-11-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
