# Generated by Django 5.1.3 on 2024-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_user_email_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_stocks',
            field=models.CharField(blank=True, choices=[('RELIANCE.NS', 'Reliance'), ('TCS.NS', 'Tcs'), ('HDFCBANK.NS', 'Hdfcbank')], max_length=30),
        ),
    ]
