# Generated by Django 5.1.3 on 2024-11-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_user_sub_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub_stocks',
        ),
    ]
